# Generated by Django 4.0.3 on 2022-04-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_city_name_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryoahf',
            name='blood_group',
            field=models.CharField(default='A+', max_length=10),
        ),
        migrations.AddField(
            model_name='granulocytes',
            name='blood_group',
            field=models.CharField(default='A+', max_length=10),
        ),
        migrations.AddField(
            model_name='plasma',
            name='bblood_group',
            field=models.CharField(default='A+', max_length=10),
        ),
        migrations.AddField(
            model_name='platelets',
            name='blood_group',
            field=models.CharField(default='A+', max_length=10),
        ),
        migrations.AddField(
            model_name='rbc',
            name='blood_group',
            field=models.CharField(default='A+', max_length=10),
        ),
    ]
