# Generated by Django 4.0.3 on 2022-04-05 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_cryoahf_blood_group_granulocytes_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryoahf',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='granulocytes',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='plasma',
            name='bblood_group',
        ),
        migrations.RemoveField(
            model_name='platelets',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='rbc',
            name='blood_group',
        ),
    ]
