# Generated by Django 4.0.3 on 2022-04-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_cryoahf_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='district',
        ),
    ]
