# Generated by Django 4.0.3 on 2022-04-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_city_country_remove_city_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
