# Generated by Django 4.0.3 on 2022-04-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_bloodcamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodcamp',
            name='name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='bloodcamp',
            name='organizer',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
