# Generated by Django 4.0.3 on 2022-04-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_bloodcamp_name_bloodcamp_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodcamp',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bloodcamp',
            name='time',
        ),
        migrations.AddField(
            model_name='bloodcamp',
            name='end_date',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='bloodcamp',
            name='end_time',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='bloodcamp',
            name='location',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='bloodcamp',
            name='start_date',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='bloodcamp',
            name='start_time',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
