# Generated by Django 4.0.3 on 2022-04-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_bloodcamp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodcamp',
            name='description',
            field=models.CharField(default='N/A', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='bloodcamp',
            name='end_date',
            field=models.CharField(default='N/A', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bloodcamp',
            name='end_time',
            field=models.CharField(default='N/A', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bloodcamp',
            name='location',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bloodcamp',
            name='name',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bloodcamp',
            name='organizer',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bloodcamp',
            name='start_date',
            field=models.CharField(default='N/A', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bloodcamp',
            name='start_time',
            field=models.CharField(default='N/A', max_length=30, null=True),
        ),
    ]
